on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: run tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Golang module init and download
        run: |
          export CI=1
          go get -u -v golang.org/x/lint/golint
          go mod download
          golint .
          go test -v -covermode=count -coverprofile=coverage.txt
